#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_SRC="${CONFIG_SRC:-$ROOT/gege/configs/twitter_16p_paper_opt.yaml}"
TRAIN_BIN="${GEGE_TRAIN_BIN:-/home/smansou2/miniconda/envs/ge2/bin/gege_train}"
EVAL_BIN="${GEGE_EVAL_BIN:-/home/smansou2/miniconda/envs/ge2/bin/gege_eval}"
SUMMARY_SCRIPT="${SUMMARY_SCRIPT:-$ROOT/scripts/summarize_benchmark_logs.py}"

EPOCHS="${EPOCHS:-3}"
RUN_EVAL="${RUN_EVAL:-0}"
RUN_NAME="${RUN_NAME:-twitter_q4_prefetch_baseline_${EPOCHS}e_$(date '+%Y%m%d_%H%M%S')}"
RUN_ROOT="${RUN_ROOT:-/tmp/$RUN_NAME}"
LOG_DIR="${LOG_DIR:-/tmp/smansou2_ge2/exp_logs}"
TRAIN_LOG="${TRAIN_LOG:-$LOG_DIR/${RUN_NAME}_train.log}"
EVAL_LOG="${EVAL_LOG:-$LOG_DIR/${RUN_NAME}_eval.log}"
MIN_FREE_GIB="${MIN_FREE_GIB:-40}"

mkdir -p "$RUN_ROOT" "$LOG_DIR"

if [[ ! -x "$TRAIN_BIN" ]]; then
  echo "missing training entrypoint: $TRAIN_BIN" >&2
  exit 1
fi

if [[ ! -x "$EVAL_BIN" ]]; then
  echo "missing eval entrypoint: $EVAL_BIN" >&2
  exit 1
fi

if [[ ! -f "$CONFIG_SRC" ]]; then
  echo "missing config: $CONFIG_SRC" >&2
  exit 1
fi

TMP_CFG="$(mktemp /tmp/twitter_q4_prefetch_XXXX.yaml)"
cleanup() {
  rm -f "$TMP_CFG"
}
trap cleanup EXIT

cp "$CONFIG_SRC" "$TMP_CFG"
perl -0pi -e "s#num_epochs:\\s*\\d+#num_epochs: $EPOCHS#; s#model_dir:\\s*.*#model_dir: $RUN_ROOT#; s#checkpoint_dir:\\s*.*#checkpoint_dir: $RUN_ROOT#; s#save_model:\\s*true#save_model: false#g; s#save_state:\\s*true#save_state: false#g" "$TMP_CFG"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export GEGE_UNIQUE_BACKEND="${GEGE_UNIQUE_BACKEND:-bitmap}"
export GEGE_UNIQUE_BITMAP_NUM_NODES="${GEGE_UNIQUE_BITMAP_NUM_NODES:-41652230}"
export GEGE_EMULATE_DOT_SINGLE_RELATION="${GEGE_EMULATE_DOT_SINGLE_RELATION:-1}"
export GEGE_MEM_PARTITION_BUFFER_PINNED_HOST="${GEGE_MEM_PARTITION_BUFFER_PINNED_HOST:-1}"
export GEGE_FAST_MAP_TENSORS="${GEGE_FAST_MAP_TENSORS:-1}"
export GEGE_PARTITION_BUFFER_LP_FAST_PATH="${GEGE_PARTITION_BUFFER_LP_FAST_PATH:-1}"
export GEGE_SINGLE_GPU_GPU_AWARE_CUSTOM="${GEGE_SINGLE_GPU_GPU_AWARE_CUSTOM:-1}"
export GEGE_OPTIMIZED_CUSTOM_SCHEDULE="${GEGE_OPTIMIZED_CUSTOM_SCHEDULE:-0}"
export GEGE_KEEP_STORAGE_HOT_BETWEEN_EPOCHS="${GEGE_KEEP_STORAGE_HOT_BETWEEN_EPOCHS:-1}"
export GEGE_GPU_ACTIVE_EDGE_SHUFFLE="${GEGE_GPU_ACTIVE_EDGE_SHUFFLE:-1}"
export GEGE_DEG_CHUNK_EXCLUSION="${GEGE_DEG_CHUNK_EXCLUSION:-1}"
export GEGE_BUCKET_STREAMING_LP="${GEGE_BUCKET_STREAMING_LP:-0}"
export GEGE_CSR_GATHER="${GEGE_CSR_GATHER:-0}"
export GEGE_CSR_UPDATE="${GEGE_CSR_UPDATE:-0}"
export GEGE_CSR_DEBUG="${GEGE_CSR_DEBUG:-0}"
export GEGE_EMPTY_CACHE_AROUND_SWAP="${GEGE_EMPTY_CACHE_AROUND_SWAP:-0}"
export GEGE_SYNC_BEFORE_SWAP="${GEGE_SYNC_BEFORE_SWAP:-0}"
export GEGE_MEM_SWAP_EVENT_SYNC="${GEGE_MEM_SWAP_EVENT_SYNC:-1}"
export GEGE_PROFILE_LOGICAL_LANE="${GEGE_PROFILE_LOGICAL_LANE:-0}"
export GEGE_FIXED_BUFFER_BITMAP_MAP="${GEGE_FIXED_BUFFER_BITMAP_MAP:-1}"
export GEGE_FIXED_BUFFER_BITMAP_REUSE_OUTPUTS="${GEGE_FIXED_BUFFER_BITMAP_REUSE_OUTPUTS:-1}"
export GEGE_FIXED_BUFFER_MASKED_UPDATE="${GEGE_FIXED_BUFFER_MASKED_UPDATE:-1}"
export GEGE_FIXED_BUFFER_MANUAL_DOT_RNS="${GEGE_FIXED_BUFFER_MANUAL_DOT_RNS:-1}"
export GEGE_SINGLE_GPU_ASYNC_ADMIT_PRELOAD="${GEGE_SINGLE_GPU_ASYNC_ADMIT_PRELOAD:-1}"
export GEGE_SINGLE_GPU_ASYNC_EVICT_WRITEBACK="${GEGE_SINGLE_GPU_ASYNC_EVICT_WRITEBACK:-0}"
export GEGE_FRAME_CACHE_HIDDEN_FRAMES="${GEGE_FRAME_CACHE_HIDDEN_FRAMES:-1}"
export GEGE_FRAME_CACHE_HIDDEN_ONLY_PRELOAD="${GEGE_FRAME_CACHE_HIDDEN_ONLY_PRELOAD:-1}"
export GEGE_FRAME_CACHE_DELAYED_STALE_WRITEBACK="${GEGE_FRAME_CACHE_DELAYED_STALE_WRITEBACK:-1}"

if [[ -z "${LD_PRELOAD:-}" && -r /lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4 ]]; then
  export LD_PRELOAD=/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
fi

RUN_FS_PATH="$(dirname "$RUN_ROOT")"
FREE_KIB="$(df -Pk "$RUN_FS_PATH" | awk 'NR==2 {print $4}')"
if [[ -n "$FREE_KIB" ]] && (( FREE_KIB < MIN_FREE_GIB * 1024 * 1024 )); then
  echo "warning: $(dirname "$RUN_ROOT") has less than ${MIN_FREE_GIB} GiB free; low free space can distort timing" >&2
fi

GIT_COMMIT="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)"
GIT_BRANCH="$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
GPU_INFO=""
if command -v nvidia-smi >/dev/null 2>&1; then
  GPU_INFO="$(nvidia-smi --query-gpu=name,memory.total,driver_version --format=csv,noheader | head -n 1)"
fi

echo "run_name=$RUN_NAME"
echo "run_root=$RUN_ROOT"
echo "config=$TMP_CFG"
echo "train_log=$TRAIN_LOG"
echo "eval_log=$EVAL_LOG"
echo "git_commit=$GIT_COMMIT"
echo "git_branch=$GIT_BRANCH"
if [[ -n "$GPU_INFO" ]]; then
  echo "gpu_info=$GPU_INFO"
fi
echo "effective_env_begin"
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
echo "GEGE_UNIQUE_BACKEND=$GEGE_UNIQUE_BACKEND"
echo "GEGE_UNIQUE_BITMAP_NUM_NODES=$GEGE_UNIQUE_BITMAP_NUM_NODES"
echo "GEGE_EMULATE_DOT_SINGLE_RELATION=$GEGE_EMULATE_DOT_SINGLE_RELATION"
echo "GEGE_MEM_PARTITION_BUFFER_PINNED_HOST=$GEGE_MEM_PARTITION_BUFFER_PINNED_HOST"
echo "GEGE_FAST_MAP_TENSORS=$GEGE_FAST_MAP_TENSORS"
echo "GEGE_PARTITION_BUFFER_LP_FAST_PATH=$GEGE_PARTITION_BUFFER_LP_FAST_PATH"
echo "GEGE_SINGLE_GPU_GPU_AWARE_CUSTOM=$GEGE_SINGLE_GPU_GPU_AWARE_CUSTOM"
echo "GEGE_OPTIMIZED_CUSTOM_SCHEDULE=$GEGE_OPTIMIZED_CUSTOM_SCHEDULE"
echo "GEGE_KEEP_STORAGE_HOT_BETWEEN_EPOCHS=$GEGE_KEEP_STORAGE_HOT_BETWEEN_EPOCHS"
echo "GEGE_GPU_ACTIVE_EDGE_SHUFFLE=$GEGE_GPU_ACTIVE_EDGE_SHUFFLE"
echo "GEGE_DEG_CHUNK_EXCLUSION=$GEGE_DEG_CHUNK_EXCLUSION"
echo "GEGE_BUCKET_STREAMING_LP=$GEGE_BUCKET_STREAMING_LP"
echo "GEGE_CSR_GATHER=$GEGE_CSR_GATHER"
echo "GEGE_CSR_UPDATE=$GEGE_CSR_UPDATE"
echo "GEGE_CSR_DEBUG=$GEGE_CSR_DEBUG"
echo "GEGE_EMPTY_CACHE_AROUND_SWAP=$GEGE_EMPTY_CACHE_AROUND_SWAP"
echo "GEGE_SYNC_BEFORE_SWAP=$GEGE_SYNC_BEFORE_SWAP"
echo "GEGE_MEM_SWAP_EVENT_SYNC=$GEGE_MEM_SWAP_EVENT_SYNC"
echo "GEGE_PROFILE_LOGICAL_LANE=$GEGE_PROFILE_LOGICAL_LANE"
echo "GEGE_FIXED_BUFFER_BITMAP_MAP=$GEGE_FIXED_BUFFER_BITMAP_MAP"
echo "GEGE_FIXED_BUFFER_BITMAP_REUSE_OUTPUTS=$GEGE_FIXED_BUFFER_BITMAP_REUSE_OUTPUTS"
echo "GEGE_FIXED_BUFFER_MASKED_UPDATE=$GEGE_FIXED_BUFFER_MASKED_UPDATE"
echo "GEGE_FIXED_BUFFER_MANUAL_DOT_RNS=$GEGE_FIXED_BUFFER_MANUAL_DOT_RNS"
echo "GEGE_SINGLE_GPU_ASYNC_ADMIT_PRELOAD=$GEGE_SINGLE_GPU_ASYNC_ADMIT_PRELOAD"
echo "GEGE_SINGLE_GPU_ASYNC_EVICT_WRITEBACK=$GEGE_SINGLE_GPU_ASYNC_EVICT_WRITEBACK"
echo "GEGE_FRAME_CACHE_HIDDEN_FRAMES=$GEGE_FRAME_CACHE_HIDDEN_FRAMES"
echo "GEGE_FRAME_CACHE_HIDDEN_ONLY_PRELOAD=$GEGE_FRAME_CACHE_HIDDEN_ONLY_PRELOAD"
echo "GEGE_FRAME_CACHE_DELAYED_STALE_WRITEBACK=$GEGE_FRAME_CACHE_DELAYED_STALE_WRITEBACK"
echo "LD_PRELOAD=${LD_PRELOAD:-}"
echo "effective_env_end"

"$TRAIN_BIN" "$TMP_CFG" 2>&1 | tee "$TRAIN_LOG"

if [[ -f "$SUMMARY_SCRIPT" ]]; then
  python3 "$SUMMARY_SCRIPT" --train-log "$TRAIN_LOG" --epochs "$EPOCHS" --format kv
fi

if [[ "$RUN_EVAL" == "1" ]]; then
  export GEGE_EVAL_CHUNKED_RANKS="${GEGE_EVAL_CHUNKED_RANKS:-1}"
  export GEGE_EVAL_NEGATIVE_CHUNK_SIZE="${GEGE_EVAL_NEGATIVE_CHUNK_SIZE:-32768}"
  "$EVAL_BIN" "$RUN_ROOT/full_config.yaml" 2>&1 | tee "$EVAL_LOG"
fi
