#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="/home/smansou2/newCode/ge2/dandelion-dev"
CONFIG="$REPO_ROOT/gege/configs/livejournal_16p_paper_opt.yaml"
ENV_BIN="/home/smansou2/miniconda/envs/ge2/bin"

export CUDA_VISIBLE_DEVICES=0
export GEGE_BUCKET_STREAMING_LP=1
export GEGE_PARTITION_BUFFER_LP_FAST_PATH=1
export GEGE_SINGLE_GPU_GPU_AWARE_CUSTOM=1
export GEGE_KEEP_STORAGE_HOT_BETWEEN_EPOCHS=1
export GEGE_FAST_MAP_TENSORS=1
export GEGE_UNIQUE_BACKEND=bitmap
export GEGE_UNIQUE_BITMAP_NUM_NODES=4847571
export GEGE_CSR_GATHER=1
export GEGE_CSR_UPDATE=1
export GEGE_CSR_DEBUG=0
export GEGE_PARTITION_BUFFER_SWAP_TIMING=1
export GEGE_PARTITION_BUFFER_SWAP_TIMING_MAX=4096
export GEGE_PARTITION_BUFFER_PIPELINE_TIMING=1
export GEGE_PARTITION_BUFFER_PIPELINE_TIMING_MAX=4096

"$ENV_BIN/gege_train" "$CONFIG"

export GEGE_EVAL_CHUNKED_RANKS=1
export GEGE_EVAL_NEGATIVE_CHUNK_SIZE=32768

"$ENV_BIN/gege_eval" "$CONFIG"
